# Generated by Django 4.1.4 on 2023-01-03 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletim4Bimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1b4', models.CharField(max_length=3)),
                ('nota2b4', models.CharField(max_length=3)),
                ('nota3b4', models.CharField(max_length=3)),
                ('bimestral4', models.CharField(max_length=3)),
                ('media4', models.CharField(max_length=3)),
                ('mediafinal', models.CharField(max_length=3)),
                ('nome_aluno_boletim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Boletim3Bimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1b3', models.CharField(max_length=3)),
                ('nota2b3', models.CharField(max_length=3)),
                ('nota3b3', models.CharField(max_length=3)),
                ('bimestral3', models.CharField(max_length=3)),
                ('media3', models.CharField(max_length=3)),
                ('nome_aluno_boletim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Boletim2Bimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1b2', models.CharField(max_length=3)),
                ('nota2b2', models.CharField(max_length=3)),
                ('nota3b2', models.CharField(max_length=3)),
                ('bimestral2', models.CharField(max_length=3)),
                ('media2', models.CharField(max_length=3)),
                ('nome_aluno_boletim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Boletim1Bimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1b1', models.CharField(max_length=3)),
                ('nota2b1', models.CharField(max_length=3)),
                ('nota3b1', models.CharField(max_length=3)),
                ('bimestral1', models.CharField(max_length=3)),
                ('media1', models.CharField(max_length=3)),
                ('nome_aluno_boletim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
            ],
        ),
    ]
