# Generated by Django 4.1.4 on 2022-12-29 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
        ('boletim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletim',
            name='nome_aluno_boletim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno'),
            preserve_default=False,
        ),
    ]
