# Generated by Django 4.1.4 on 2022-12-15 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='turno',
        ),
    ]
