# Generated by Django 4.1.4 on 2022-12-29 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=100)),
                ('cpf_aluno', models.CharField(max_length=11)),
                ('rg_aluno', models.CharField(max_length=7)),
                ('email_aluno', models.EmailField(max_length=254)),
                ('endereco_aluno', models.CharField(max_length=50)),
                ('contato_aluno', models.CharField(max_length=11)),
                ('turno_aluno', models.CharField(max_length=50)),
                ('data_nascimento_aluno', models.DateField()),
                ('data_entrada_aluno', models.DateField(default=datetime.date.today)),
                ('raca_aluno', models.CharField(max_length=50)),
                ('sexo_aluno', models.CharField(max_length=50)),
            ],
        ),
    ]
