# Generated by Django 4.1.4 on 2022-12-29 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prof', models.CharField(max_length=50)),
                ('cpf_prof', models.CharField(max_length=11)),
                ('rg_prof', models.CharField(max_length=7)),
                ('email_prof', models.EmailField(max_length=254)),
                ('endereco_prof', models.CharField(max_length=50)),
                ('formacao_prof', models.CharField(max_length=50)),
                ('contato_prof', models.CharField(max_length=11)),
                ('turno_prof', models.CharField(max_length=50)),
                ('data_nascimento_prof', models.DateField()),
                ('data_entrada_prof', models.DateField(default=datetime.date.today)),
                ('raca_prof', models.CharField(max_length=50)),
                ('sexo_prof', models.CharField(max_length=50)),
            ],
        ),
    ]
