# Generated by Django 4.1.4 on 2023-01-03 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='aluno_turma',
        ),
    ]
