# Generated by Django 4.1.4 on 2022-12-30 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='aluno_turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno'),
            preserve_default=False,
        ),
    ]
