# Generated by Django 4.1.4 on 2023-01-04 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('turma', '0004_alter_turma_ano_turma_alter_turma_dia_turma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='disciplina_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.disciplina'),
        ),
    ]
