# Generated by Django 4.1.4 on 2023-01-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0005_alter_turma_disciplina_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='ano_turma',
            field=models.CharField(choices=[('', 'Defina o ano'), ('1º ano', '1º ano'), ('2º ano', '2º ano'), ('3º ano', '3º ano'), ('4º ano', '4º ano'), ('5º ano', '5º ano'), ('6º ano', '6º ano'), ('7º ano', '7º ano'), ('8º ano', '8º ano'), ('9º ano', '9º ano')], max_length=20),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dia_turma',
            field=models.CharField(choices=[('', 'Defina o dia'), ('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='turma',
            name='etapa_turma',
            field=models.CharField(choices=[('', 'Defina a etapa'), ('Fundamental I', 'Fundamental I'), ('Fundamental II', 'Fundamental II'), ('Ensino Médio', 'Ensino Médio')], max_length=20),
        ),
    ]
